### TOPIC SEND
POST http://localhost:8080/api/topic/send
Content-Type: application/json

"{{$datetime iso8601}} carletto "

### TOPIC SEND
POST http://localhost:8080/api/queue/send
Content-Type: application/json

"{{$datetime iso8601}} carletto "

### RECEIVE TOPIC
GET http://localhost:8080/api/topic/receive
Content-Type: application/json

### RECEIVE QUEUE
GET http://localhost:8080/api/queue/receive
Content-Type: application/json




